FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

# Copy Angular build
COPY ./artifacts/frontend/demo /demo/angular/dist/demo

# Copy Nginx config
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
